# Generated by Django 5.2.8 on 2025-12-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('DonCat', 'a'), ('Wiskas', 'b'), ('Felix', 'c')], default='single', max_length=10),
        ),
    ]
