# Generated by Django 5.2.8 on 2026-01-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_alter_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Apellido')),
                ('age', models.PositiveBigIntegerField(verbose_name='Edad')),
            ],
        ),
    ]
