# Generated by Django 5.2.8 on 2026-01-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titulo del Libro')),
                ('codigo_unique', models.CharField(max_length=10, unique=True, verbose_name='Codigp Único')),
                ('author', models.ManyToManyField(to='pruebas.author')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
