# Generated by Django 5.2.8 on 2026-01-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0007_remove_book_author_alter_book_codigo_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='pruebas.author'),
        ),
    ]
